// Generated by CoffeeScript 1.6.3
(function() {
  var array, item, myFunction, _i, _len;

  myFunction = function(arg) {
    return arg + '!';
  };

  array = ['one', 'two', 'three', 'four'];

  for (_i = 0, _len = array.length; _i < _len; _i++) {
    item = array[_i];
    console.log(myFunction(item));
  }

}).call(this);
